#! /usr/bin/python
# encoding: utf-8


python_cflags =['-fno-strict-aliasing' ,'-O2' ,'-g' ,'-pipe', '-Wall' ,'-Werror=format-security' ,'-Wp,-D_FORTIFY_SOURCE=2' ,'-fexceptions', '-fstack-protector-strong', '--param=ssp-buffer-size=4', '-grecord-gcc-switches', '-m64', '-mtune=generic', '-D_GNU_SOURCE', '-fPIC', '-fwrapv', '-DNDEBUG']
python_ldflags = ['-lpthread', '-ldl' ,'-lutil' ,'-lm' ,'-lpython2.7' ,'-Xlinker' ,'-export-dynamic']

python_cflags.append("-std=c++11")

def build(bld):
	bld.program(
                source       = 'main.cpp',
                target       = 'python_embed',
                includes     = ['/usr/include/python2.7'],
                linkflags    = python_ldflags,
                #rpath        = ['/opt/kde/lib']
                cflags       = python_cflags,
                cxxflags     = python_cflags,
	)  
 
