#! /usr/bin/python
# encoding: utf-8

top = '.'
out = '_build'

sub_porject = ['test', 'python_embed']

def options(opt):
        opt.load('compiler_cxx qt5')
def configure(cnf):
        cnf.load('compiler_cxx qt5')

def build(ctx):
	ctx.recurse(sub_porject)       
 
